[package]
name = "runmc"
version = "0.0.12"
description = "A Minecraft launcher"
authors = [ "Manuel Quarneti <manuelquarneti@gmail.com>" ]
license = "MIT"
repository = "https://github.com/mq1/runmc"
default-run = "runmc"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = "1.0.0-beta.1"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
reqwest = { version = "0.11", features = [ "json" ] }
serde_yaml = "0.8"
uuid = { version = "0.8", features = [ "v4" ] }

  [dependencies.tauri]
  version = "1.0.0-beta.4"
features = ["updater"]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "z"
