// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Instance: typeof import('./src/components/instance.vue')['default']
    NavLink: typeof import('./src/components/nav-link.vue')['default']
  }
}

export { }
