name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build-artifacs:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: build
        run: |
          npm i
          npm run build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}

      - uses: softprops/action-gh-release@v1
        if: matrix.platform == 'ubuntu-latest'
        with:
          files: ./target/release/bundle/appimage/runmc_*.AppImage.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v1
        if: matrix.platform == 'windows-latest'
        with:
          files: ./target/release/bundle/msi/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v1
        if: matrix.platform == 'macos-latest'
        with:
          files: ./target/release/bundle/macos/runmc_*.app.tar.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release json
        uses: softprops/action-gh-release@v1
        with:
          files: ./release.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
